name: Rush
version: 1.0.0
author: Walidoux
website: https://tl-events.fr
main: io.github.rush.Main
api-version: "26.1"

dependencies:
  server:
    FastAsyncWorldEdit:
      load: BEFORE
      required: true
      join-classpath: true
    packetevents:
      load: BEFORE
      required: true
      join-classpath: true
    HologramLib:
      load: BEFORE
      required: true
      join-classpath: true
    CraftEngine:
      load: BEFORE
      required: false
      join-classpath: true

translations:
  - "translations/fr_fr.json"
