name: Rush
version: 1.0.0
main: io.github.rush.Main
api-version: 1.21
softdepend:
  - WorldEdit
  - GMusic

commands:
  rush:levels:
    description: Commands for testing the level system
    usage: /rush:levels
