// Type definitions for rush 1.0.0 generated by jtsgen
// Definitions by: unknown <unknown>


declare namespace rush {
  export enum IslandType {
    FOUR_ISLANDS,
    EIGHT_ISLANDS
  }

  export enum Color {
    WHITE,
    ORANGE,
    MAGENTA,
    LIGHT_BLUE,
    YELLOW,
    LIME,
    PINK,
    GRAY,
    LIGHT_GRAY,
    CYAN,
    PURPLE,
    BLUE,
    BROWN,
    GREEN,
    RED,
    BLACK
  }

  export enum TeamSize {
    VS1,
    VS2,
    VS3,
    VS4
  }

  /**
   *  NOTE: ARCHIVED is not included within the lifecycle as a state
   *  of a GameRoom instance since it is scheduled for removal and world cleanup
   */
  export enum GameState {
    CREATING,
    WAITING,
    RUNNING,
    STOPPED
  }

 }
